# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bnet/chat_types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bnet/chat_types.proto',
  package='bnet.protocol.chat',
  serialized_pb=_b('\n\x15\x62net/chat_types.proto\x12\x12\x62net.protocol.chat\"n\n\x0c\x43hannelState\x12\x10\n\x08identity\x18\x01 \x01(\t\x12\x0f\n\x07program\x18\x02 \x01(\x07\x12\x0e\n\x06locale\x18\x03 \x01(\x07\x12\x15\n\x06public\x18\x04 \x01(\x08:\x05\x66\x61lse\x12\x14\n\x0c\x62ucket_index\x18\x05 \x01(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CHANNELSTATE = _descriptor.Descriptor(
  name='ChannelState',
  full_name='bnet.protocol.chat.ChannelState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identity', full_name='bnet.protocol.chat.ChannelState.identity', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='program', full_name='bnet.protocol.chat.ChannelState.program', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='locale', full_name='bnet.protocol.chat.ChannelState.locale', index=2,
      number=3, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='public', full_name='bnet.protocol.chat.ChannelState.public', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bucket_index', full_name='bnet.protocol.chat.ChannelState.bucket_index', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=155,
)

DESCRIPTOR.message_types_by_name['ChannelState'] = _CHANNELSTATE

ChannelState = _reflection.GeneratedProtocolMessageType('ChannelState', (_message.Message,), dict(
  DESCRIPTOR = _CHANNELSTATE,
  __module__ = 'bnet.chat_types_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.chat.ChannelState)
  ))
_sym_db.RegisterMessage(ChannelState)


# @@protoc_insertion_point(module_scope)
