# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bnet/connection_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bnet import content_handle_pb2 as bnet_dot_content__handle__pb2
from bnet import rpc_pb2 as bnet_dot_rpc__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bnet/connection_service.proto',
  package='bnet.protocol.connection',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x1d\x62net/connection_service.proto\x12\x18\x62net.protocol.connection\x1a\x19\x62net/content_handle.proto\x1a\x0e\x62net/rpc.proto\"z\n\x0e\x43onnectRequest\x12+\n\tclient_id\x18\x01 \x01(\x0b\x32\x18.bnet.protocol.ProcessId\x12;\n\x0c\x62ind_request\x18\x02 \x01(\x0b\x32%.bnet.protocol.connection.BindRequest\"X\n ConnectionMeteringContentHandles\x12\x34\n\x0e\x63ontent_handle\x18\x01 \x03(\x0b\x32\x1c.bnet.protocol.ContentHandle\"\xae\x02\n\x0f\x43onnectResponse\x12+\n\tserver_id\x18\x01 \x02(\x0b\x32\x18.bnet.protocol.ProcessId\x12+\n\tclient_id\x18\x02 \x01(\x0b\x32\x18.bnet.protocol.ProcessId\x12\x13\n\x0b\x62ind_result\x18\x03 \x01(\r\x12=\n\rbind_response\x18\x04 \x01(\x0b\x32&.bnet.protocol.connection.BindResponse\x12X\n\x14\x63ontent_handle_array\x18\x05 \x01(\x0b\x32:.bnet.protocol.connection.ConnectionMeteringContentHandles\x12\x13\n\x0bserver_time\x18\x06 \x01(\x04\"(\n\x0c\x42oundService\x12\x0c\n\x04hash\x18\x01 \x02(\x07\x12\n\n\x02id\x18\x02 \x02(\r\"n\n\x0b\x42indRequest\x12\x1d\n\x15imported_service_hash\x18\x01 \x03(\x07\x12@\n\x10\x65xported_service\x18\x02 \x03(\x0b\x32&.bnet.protocol.connection.BoundService\"/\n\x0c\x42indResponse\x12\x1f\n\x13imported_service_id\x18\x01 \x03(\rB\x02\x10\x01\"I\n\x0b\x45\x63hoRequest\x12\x0c\n\x04time\x18\x01 \x01(\x06\x12\x1b\n\x0cnetwork_only\x18\x02 \x01(\x08:\x05\x66\x61lse\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\"-\n\x0c\x45\x63hoResponse\x12\x0c\n\x04time\x18\x01 \x01(\x06\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"\'\n\x11\x44isconnectRequest\x12\x12\n\nerror_code\x18\x01 \x02(\r\"<\n\x16\x44isconnectNotification\x12\x12\n\nerror_code\x18\x01 \x02(\r\x12\x0e\n\x06reason\x18\x02 \x01(\t\"\x10\n\x0e\x45ncryptRequest'
  ,
  dependencies=[bnet_dot_content__handle__pb2.DESCRIPTOR,bnet_dot_rpc__pb2.DESCRIPTOR,])




_CONNECTREQUEST = _descriptor.Descriptor(
  name='ConnectRequest',
  full_name='bnet.protocol.connection.ConnectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='bnet.protocol.connection.ConnectRequest.client_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bind_request', full_name='bnet.protocol.connection.ConnectRequest.bind_request', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=224,
)


_CONNECTIONMETERINGCONTENTHANDLES = _descriptor.Descriptor(
  name='ConnectionMeteringContentHandles',
  full_name='bnet.protocol.connection.ConnectionMeteringContentHandles',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content_handle', full_name='bnet.protocol.connection.ConnectionMeteringContentHandles.content_handle', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=314,
)


_CONNECTRESPONSE = _descriptor.Descriptor(
  name='ConnectResponse',
  full_name='bnet.protocol.connection.ConnectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='server_id', full_name='bnet.protocol.connection.ConnectResponse.server_id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='bnet.protocol.connection.ConnectResponse.client_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bind_result', full_name='bnet.protocol.connection.ConnectResponse.bind_result', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bind_response', full_name='bnet.protocol.connection.ConnectResponse.bind_response', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content_handle_array', full_name='bnet.protocol.connection.ConnectResponse.content_handle_array', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='server_time', full_name='bnet.protocol.connection.ConnectResponse.server_time', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=619,
)


_BOUNDSERVICE = _descriptor.Descriptor(
  name='BoundService',
  full_name='bnet.protocol.connection.BoundService',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='bnet.protocol.connection.BoundService.hash', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='bnet.protocol.connection.BoundService.id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=621,
  serialized_end=661,
)


_BINDREQUEST = _descriptor.Descriptor(
  name='BindRequest',
  full_name='bnet.protocol.connection.BindRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imported_service_hash', full_name='bnet.protocol.connection.BindRequest.imported_service_hash', index=0,
      number=1, type=7, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exported_service', full_name='bnet.protocol.connection.BindRequest.exported_service', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=663,
  serialized_end=773,
)


_BINDRESPONSE = _descriptor.Descriptor(
  name='BindResponse',
  full_name='bnet.protocol.connection.BindResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imported_service_id', full_name='bnet.protocol.connection.BindResponse.imported_service_id', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=775,
  serialized_end=822,
)


_ECHOREQUEST = _descriptor.Descriptor(
  name='EchoRequest',
  full_name='bnet.protocol.connection.EchoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='bnet.protocol.connection.EchoRequest.time', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='network_only', full_name='bnet.protocol.connection.EchoRequest.network_only', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='bnet.protocol.connection.EchoRequest.payload', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=824,
  serialized_end=897,
)


_ECHORESPONSE = _descriptor.Descriptor(
  name='EchoResponse',
  full_name='bnet.protocol.connection.EchoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='bnet.protocol.connection.EchoResponse.time', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='bnet.protocol.connection.EchoResponse.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=899,
  serialized_end=944,
)


_DISCONNECTREQUEST = _descriptor.Descriptor(
  name='DisconnectRequest',
  full_name='bnet.protocol.connection.DisconnectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='bnet.protocol.connection.DisconnectRequest.error_code', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=946,
  serialized_end=985,
)


_DISCONNECTNOTIFICATION = _descriptor.Descriptor(
  name='DisconnectNotification',
  full_name='bnet.protocol.connection.DisconnectNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='bnet.protocol.connection.DisconnectNotification.error_code', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reason', full_name='bnet.protocol.connection.DisconnectNotification.reason', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=987,
  serialized_end=1047,
)


_ENCRYPTREQUEST = _descriptor.Descriptor(
  name='EncryptRequest',
  full_name='bnet.protocol.connection.EncryptRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1049,
  serialized_end=1065,
)

_CONNECTREQUEST.fields_by_name['client_id'].message_type = bnet_dot_rpc__pb2._PROCESSID
_CONNECTREQUEST.fields_by_name['bind_request'].message_type = _BINDREQUEST
_CONNECTIONMETERINGCONTENTHANDLES.fields_by_name['content_handle'].message_type = bnet_dot_content__handle__pb2._CONTENTHANDLE
_CONNECTRESPONSE.fields_by_name['server_id'].message_type = bnet_dot_rpc__pb2._PROCESSID
_CONNECTRESPONSE.fields_by_name['client_id'].message_type = bnet_dot_rpc__pb2._PROCESSID
_CONNECTRESPONSE.fields_by_name['bind_response'].message_type = _BINDRESPONSE
_CONNECTRESPONSE.fields_by_name['content_handle_array'].message_type = _CONNECTIONMETERINGCONTENTHANDLES
_BINDREQUEST.fields_by_name['exported_service'].message_type = _BOUNDSERVICE
DESCRIPTOR.message_types_by_name['ConnectRequest'] = _CONNECTREQUEST
DESCRIPTOR.message_types_by_name['ConnectionMeteringContentHandles'] = _CONNECTIONMETERINGCONTENTHANDLES
DESCRIPTOR.message_types_by_name['ConnectResponse'] = _CONNECTRESPONSE
DESCRIPTOR.message_types_by_name['BoundService'] = _BOUNDSERVICE
DESCRIPTOR.message_types_by_name['BindRequest'] = _BINDREQUEST
DESCRIPTOR.message_types_by_name['BindResponse'] = _BINDRESPONSE
DESCRIPTOR.message_types_by_name['EchoRequest'] = _ECHOREQUEST
DESCRIPTOR.message_types_by_name['EchoResponse'] = _ECHORESPONSE
DESCRIPTOR.message_types_by_name['DisconnectRequest'] = _DISCONNECTREQUEST
DESCRIPTOR.message_types_by_name['DisconnectNotification'] = _DISCONNECTNOTIFICATION
DESCRIPTOR.message_types_by_name['EncryptRequest'] = _ENCRYPTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnectRequest = _reflection.GeneratedProtocolMessageType('ConnectRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTREQUEST,
  '__module__' : 'bnet.connection_service_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.connection.ConnectRequest)
  })
_sym_db.RegisterMessage(ConnectRequest)

ConnectionMeteringContentHandles = _reflection.GeneratedProtocolMessageType('ConnectionMeteringContentHandles', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONMETERINGCONTENTHANDLES,
  '__module__' : 'bnet.connection_service_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.connection.ConnectionMeteringContentHandles)
  })
_sym_db.RegisterMessage(ConnectionMeteringContentHandles)

ConnectResponse = _reflection.GeneratedProtocolMessageType('ConnectResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTRESPONSE,
  '__module__' : 'bnet.connection_service_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.connection.ConnectResponse)
  })
_sym_db.RegisterMessage(ConnectResponse)

BoundService = _reflection.GeneratedProtocolMessageType('BoundService', (_message.Message,), {
  'DESCRIPTOR' : _BOUNDSERVICE,
  '__module__' : 'bnet.connection_service_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.connection.BoundService)
  })
_sym_db.RegisterMessage(BoundService)

BindRequest = _reflection.GeneratedProtocolMessageType('BindRequest', (_message.Message,), {
  'DESCRIPTOR' : _BINDREQUEST,
  '__module__' : 'bnet.connection_service_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.connection.BindRequest)
  })
_sym_db.RegisterMessage(BindRequest)

BindResponse = _reflection.GeneratedProtocolMessageType('BindResponse', (_message.Message,), {
  'DESCRIPTOR' : _BINDRESPONSE,
  '__module__' : 'bnet.connection_service_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.connection.BindResponse)
  })
_sym_db.RegisterMessage(BindResponse)

EchoRequest = _reflection.GeneratedProtocolMessageType('EchoRequest', (_message.Message,), {
  'DESCRIPTOR' : _ECHOREQUEST,
  '__module__' : 'bnet.connection_service_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.connection.EchoRequest)
  })
_sym_db.RegisterMessage(EchoRequest)

EchoResponse = _reflection.GeneratedProtocolMessageType('EchoResponse', (_message.Message,), {
  'DESCRIPTOR' : _ECHORESPONSE,
  '__module__' : 'bnet.connection_service_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.connection.EchoResponse)
  })
_sym_db.RegisterMessage(EchoResponse)

DisconnectRequest = _reflection.GeneratedProtocolMessageType('DisconnectRequest', (_message.Message,), {
  'DESCRIPTOR' : _DISCONNECTREQUEST,
  '__module__' : 'bnet.connection_service_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.connection.DisconnectRequest)
  })
_sym_db.RegisterMessage(DisconnectRequest)

DisconnectNotification = _reflection.GeneratedProtocolMessageType('DisconnectNotification', (_message.Message,), {
  'DESCRIPTOR' : _DISCONNECTNOTIFICATION,
  '__module__' : 'bnet.connection_service_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.connection.DisconnectNotification)
  })
_sym_db.RegisterMessage(DisconnectNotification)

EncryptRequest = _reflection.GeneratedProtocolMessageType('EncryptRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENCRYPTREQUEST,
  '__module__' : 'bnet.connection_service_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.connection.EncryptRequest)
  })
_sym_db.RegisterMessage(EncryptRequest)


_BINDRESPONSE.fields_by_name['imported_service_id']._options = None
# @@protoc_insertion_point(module_scope)
