# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bnet/content_handle.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bnet/content_handle.proto',
  package='bnet.protocol',
  serialized_pb=_b('\n\x19\x62net/content_handle.proto\x12\rbnet.protocol\"O\n\rContentHandle\x12\x0e\n\x06region\x18\x01 \x02(\x07\x12\r\n\x05usage\x18\x02 \x02(\x07\x12\x0c\n\x04hash\x18\x03 \x02(\x0c\x12\x11\n\tproto_url\x18\x04 \x01(\t\"\x1b\n\x04Path\x12\x13\n\x07ordinal\x18\x01 \x03(\rB\x02\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CONTENTHANDLE = _descriptor.Descriptor(
  name='ContentHandle',
  full_name='bnet.protocol.ContentHandle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='region', full_name='bnet.protocol.ContentHandle.region', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='usage', full_name='bnet.protocol.ContentHandle.usage', index=1,
      number=2, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hash', full_name='bnet.protocol.ContentHandle.hash', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='proto_url', full_name='bnet.protocol.ContentHandle.proto_url', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=123,
)


_PATH = _descriptor.Descriptor(
  name='Path',
  full_name='bnet.protocol.Path',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ordinal', full_name='bnet.protocol.Path.ordinal', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=152,
)

DESCRIPTOR.message_types_by_name['ContentHandle'] = _CONTENTHANDLE
DESCRIPTOR.message_types_by_name['Path'] = _PATH

ContentHandle = _reflection.GeneratedProtocolMessageType('ContentHandle', (_message.Message,), dict(
  DESCRIPTOR = _CONTENTHANDLE,
  __module__ = 'bnet.content_handle_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.ContentHandle)
  ))
_sym_db.RegisterMessage(ContentHandle)

Path = _reflection.GeneratedProtocolMessageType('Path', (_message.Message,), dict(
  DESCRIPTOR = _PATH,
  __module__ = 'bnet.content_handle_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.Path)
  ))
_sym_db.RegisterMessage(Path)


_PATH.fields_by_name['ordinal'].has_options = True
_PATH.fields_by_name['ordinal']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
