# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bnet/game_utilities_types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bnet.attribute_pb2
import bnet.entity_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bnet/game_utilities_types.proto',
  package='bnet.protocol.game_utilities',
  serialized_pb=_b('\n\x1f\x62net/game_utilities_types.proto\x12\x1c\x62net.protocol.game_utilities\x1a\x14\x62net/attribute.proto\x1a\x11\x62net/entity.proto\"\x83\x01\n\x0fPlayerVariables\x12)\n\x08identity\x18\x01 \x02(\x0b\x32\x17.bnet.protocol.Identity\x12\x0e\n\x06rating\x18\x02 \x01(\x01\x12\x35\n\tattribute\x18\x03 \x03(\x0b\x32\".bnet.protocol.attribute.Attribute')
  ,
  dependencies=[bnet.attribute_pb2.DESCRIPTOR,bnet.entity_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PLAYERVARIABLES = _descriptor.Descriptor(
  name='PlayerVariables',
  full_name='bnet.protocol.game_utilities.PlayerVariables',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identity', full_name='bnet.protocol.game_utilities.PlayerVariables.identity', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rating', full_name='bnet.protocol.game_utilities.PlayerVariables.rating', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attribute', full_name='bnet.protocol.game_utilities.PlayerVariables.attribute', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=238,
)

_PLAYERVARIABLES.fields_by_name['identity'].message_type = bnet.entity_pb2._IDENTITY
_PLAYERVARIABLES.fields_by_name['attribute'].message_type = bnet.attribute_pb2._ATTRIBUTE
DESCRIPTOR.message_types_by_name['PlayerVariables'] = _PLAYERVARIABLES

PlayerVariables = _reflection.GeneratedProtocolMessageType('PlayerVariables', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERVARIABLES,
  __module__ = 'bnet.game_utilities_types_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.game_utilities.PlayerVariables)
  ))
_sym_db.RegisterMessage(PlayerVariables)


# @@protoc_insertion_point(module_scope)
