# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bnet/game_master_types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bnet.attribute_pb2
import bnet.entity_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bnet/game_master_types.proto',
  package='bnet.protocol.game_master',
  serialized_pb=_b('\n\x1c\x62net/game_master_types.proto\x12\x19\x62net.protocol.game_master\x1a\x14\x62net/attribute.proto\x1a\x11\x62net/entity.proto\"j\n\x06Player\x12)\n\x08identity\x18\x01 \x01(\x0b\x32\x17.bnet.protocol.Identity\x12\x35\n\tattribute\x18\x02 \x03(\x0b\x32\".bnet.protocol.attribute.Attribute\"\x9b\x01\n\x0b\x43onnectInfo\x12*\n\tmember_id\x18\x01 \x02(\x0b\x32\x17.bnet.protocol.EntityId\x12\x0c\n\x04host\x18\x02 \x02(\t\x12\x0c\n\x04port\x18\x03 \x02(\x05\x12\r\n\x05token\x18\x04 \x01(\x0c\x12\x35\n\tattribute\x18\x05 \x03(\x0b\x32\".bnet.protocol.attribute.Attribute\"\xfd\x02\n\x0fGameStatsBucket\x12\x15\n\nbucket_min\x18\x01 \x01(\x02:\x01\x30\x12 \n\nbucket_max\x18\x02 \x01(\x02:\x0c\x34.294967e+09\x12\x1c\n\x11wait_milliseconds\x18\x03 \x01(\r:\x01\x30\x12\x19\n\x0egames_per_hour\x18\x04 \x01(\r:\x01\x30\x12\x17\n\x0c\x61\x63tive_games\x18\x05 \x01(\r:\x01\x30\x12\x19\n\x0e\x61\x63tive_players\x18\x06 \x01(\r:\x01\x30\x12\x18\n\rforming_games\x18\x07 \x01(\r:\x01\x30\x12\x1a\n\x0fwaiting_players\x18\x08 \x01(\r:\x01\x30\x12\x1e\n\x13open_joinable_games\x18\t \x01(\r:\x01\x30\x12)\n\x1eplayers_in_open_joinable_games\x18\n \x01(\r:\x01\x30\x12\x1b\n\x10open_games_total\x18\x0b \x01(\r:\x01\x30\x12&\n\x1bplayers_in_open_games_total\x18\x0c \x01(\r:\x01\x30\"\xe1\x01\n\x16GameFactoryDescription\x12\n\n\x02id\x18\x01 \x02(\x06\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x35\n\tattribute\x18\x03 \x03(\x0b\x32\".bnet.protocol.attribute.Attribute\x12@\n\x0cstats_bucket\x18\x04 \x03(\x0b\x32*.bnet.protocol.game_master.GameStatsBucket\x12\x16\n\x0bunseeded_id\x18\x05 \x01(\x06:\x01\x30\x12\x1c\n\x0e\x61llow_queueing\x18\x06 \x01(\x08:\x04true\"J\n\nGameHandle\x12\x12\n\nfactory_id\x18\x01 \x02(\x06\x12(\n\x07game_id\x18\x02 \x02(\x0b\x32\x17.bnet.protocol.EntityId\"s\n\x16\x43\x61ncelGameEntryRequest\x12\x12\n\nrequest_id\x18\x01 \x02(\x06\x12\x12\n\nfactory_id\x18\x02 \x01(\x06\x12\x31\n\x06player\x18\x03 \x03(\x0b\x32!.bnet.protocol.game_master.Player')
  ,
  dependencies=[bnet.attribute_pb2.DESCRIPTOR,bnet.entity_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PLAYER = _descriptor.Descriptor(
  name='Player',
  full_name='bnet.protocol.game_master.Player',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identity', full_name='bnet.protocol.game_master.Player.identity', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attribute', full_name='bnet.protocol.game_master.Player.attribute', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=206,
)


_CONNECTINFO = _descriptor.Descriptor(
  name='ConnectInfo',
  full_name='bnet.protocol.game_master.ConnectInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='member_id', full_name='bnet.protocol.game_master.ConnectInfo.member_id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='host', full_name='bnet.protocol.game_master.ConnectInfo.host', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='bnet.protocol.game_master.ConnectInfo.port', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='bnet.protocol.game_master.ConnectInfo.token', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attribute', full_name='bnet.protocol.game_master.ConnectInfo.attribute', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=364,
)


_GAMESTATSBUCKET = _descriptor.Descriptor(
  name='GameStatsBucket',
  full_name='bnet.protocol.game_master.GameStatsBucket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bucket_min', full_name='bnet.protocol.game_master.GameStatsBucket.bucket_min', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bucket_max', full_name='bnet.protocol.game_master.GameStatsBucket.bucket_max', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=4.294967e+09,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wait_milliseconds', full_name='bnet.protocol.game_master.GameStatsBucket.wait_milliseconds', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='games_per_hour', full_name='bnet.protocol.game_master.GameStatsBucket.games_per_hour', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='active_games', full_name='bnet.protocol.game_master.GameStatsBucket.active_games', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='active_players', full_name='bnet.protocol.game_master.GameStatsBucket.active_players', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='forming_games', full_name='bnet.protocol.game_master.GameStatsBucket.forming_games', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='waiting_players', full_name='bnet.protocol.game_master.GameStatsBucket.waiting_players', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='open_joinable_games', full_name='bnet.protocol.game_master.GameStatsBucket.open_joinable_games', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='players_in_open_joinable_games', full_name='bnet.protocol.game_master.GameStatsBucket.players_in_open_joinable_games', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='open_games_total', full_name='bnet.protocol.game_master.GameStatsBucket.open_games_total', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='players_in_open_games_total', full_name='bnet.protocol.game_master.GameStatsBucket.players_in_open_games_total', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=748,
)


_GAMEFACTORYDESCRIPTION = _descriptor.Descriptor(
  name='GameFactoryDescription',
  full_name='bnet.protocol.game_master.GameFactoryDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='bnet.protocol.game_master.GameFactoryDescription.id', index=0,
      number=1, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='bnet.protocol.game_master.GameFactoryDescription.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attribute', full_name='bnet.protocol.game_master.GameFactoryDescription.attribute', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stats_bucket', full_name='bnet.protocol.game_master.GameFactoryDescription.stats_bucket', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unseeded_id', full_name='bnet.protocol.game_master.GameFactoryDescription.unseeded_id', index=4,
      number=5, type=6, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='allow_queueing', full_name='bnet.protocol.game_master.GameFactoryDescription.allow_queueing', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=751,
  serialized_end=976,
)


_GAMEHANDLE = _descriptor.Descriptor(
  name='GameHandle',
  full_name='bnet.protocol.game_master.GameHandle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='factory_id', full_name='bnet.protocol.game_master.GameHandle.factory_id', index=0,
      number=1, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='game_id', full_name='bnet.protocol.game_master.GameHandle.game_id', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=978,
  serialized_end=1052,
)


_CANCELGAMEENTRYREQUEST = _descriptor.Descriptor(
  name='CancelGameEntryRequest',
  full_name='bnet.protocol.game_master.CancelGameEntryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='bnet.protocol.game_master.CancelGameEntryRequest.request_id', index=0,
      number=1, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='factory_id', full_name='bnet.protocol.game_master.CancelGameEntryRequest.factory_id', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player', full_name='bnet.protocol.game_master.CancelGameEntryRequest.player', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1054,
  serialized_end=1169,
)

_PLAYER.fields_by_name['identity'].message_type = bnet.entity_pb2._IDENTITY
_PLAYER.fields_by_name['attribute'].message_type = bnet.attribute_pb2._ATTRIBUTE
_CONNECTINFO.fields_by_name['member_id'].message_type = bnet.entity_pb2._ENTITYID
_CONNECTINFO.fields_by_name['attribute'].message_type = bnet.attribute_pb2._ATTRIBUTE
_GAMEFACTORYDESCRIPTION.fields_by_name['attribute'].message_type = bnet.attribute_pb2._ATTRIBUTE
_GAMEFACTORYDESCRIPTION.fields_by_name['stats_bucket'].message_type = _GAMESTATSBUCKET
_GAMEHANDLE.fields_by_name['game_id'].message_type = bnet.entity_pb2._ENTITYID
_CANCELGAMEENTRYREQUEST.fields_by_name['player'].message_type = _PLAYER
DESCRIPTOR.message_types_by_name['Player'] = _PLAYER
DESCRIPTOR.message_types_by_name['ConnectInfo'] = _CONNECTINFO
DESCRIPTOR.message_types_by_name['GameStatsBucket'] = _GAMESTATSBUCKET
DESCRIPTOR.message_types_by_name['GameFactoryDescription'] = _GAMEFACTORYDESCRIPTION
DESCRIPTOR.message_types_by_name['GameHandle'] = _GAMEHANDLE
DESCRIPTOR.message_types_by_name['CancelGameEntryRequest'] = _CANCELGAMEENTRYREQUEST

Player = _reflection.GeneratedProtocolMessageType('Player', (_message.Message,), dict(
  DESCRIPTOR = _PLAYER,
  __module__ = 'bnet.game_master_types_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.game_master.Player)
  ))
_sym_db.RegisterMessage(Player)

ConnectInfo = _reflection.GeneratedProtocolMessageType('ConnectInfo', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTINFO,
  __module__ = 'bnet.game_master_types_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.game_master.ConnectInfo)
  ))
_sym_db.RegisterMessage(ConnectInfo)

GameStatsBucket = _reflection.GeneratedProtocolMessageType('GameStatsBucket', (_message.Message,), dict(
  DESCRIPTOR = _GAMESTATSBUCKET,
  __module__ = 'bnet.game_master_types_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.game_master.GameStatsBucket)
  ))
_sym_db.RegisterMessage(GameStatsBucket)

GameFactoryDescription = _reflection.GeneratedProtocolMessageType('GameFactoryDescription', (_message.Message,), dict(
  DESCRIPTOR = _GAMEFACTORYDESCRIPTION,
  __module__ = 'bnet.game_master_types_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.game_master.GameFactoryDescription)
  ))
_sym_db.RegisterMessage(GameFactoryDescription)

GameHandle = _reflection.GeneratedProtocolMessageType('GameHandle', (_message.Message,), dict(
  DESCRIPTOR = _GAMEHANDLE,
  __module__ = 'bnet.game_master_types_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.game_master.GameHandle)
  ))
_sym_db.RegisterMessage(GameHandle)

CancelGameEntryRequest = _reflection.GeneratedProtocolMessageType('CancelGameEntryRequest', (_message.Message,), dict(
  DESCRIPTOR = _CANCELGAMEENTRYREQUEST,
  __module__ = 'bnet.game_master_types_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.game_master.CancelGameEntryRequest)
  ))
_sym_db.RegisterMessage(CancelGameEntryRequest)


# @@protoc_insertion_point(module_scope)
