# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bnet/notification_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bnet.attribute_pb2
import bnet.entity_pb2
import bnet.rpc_pb2
import bnet.smth_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bnet/notification_service.proto',
  package='bnet.protocol.notification',
  serialized_pb=_b('\n\x1f\x62net/notification_service.proto\x12\x1a\x62net.protocol.notification\x1a\x14\x62net/attribute.proto\x1a\x11\x62net/entity.proto\x1a\x0e\x62net/rpc.proto\"\xae\x02\n\x0cNotification\x12*\n\tsender_id\x18\x01 \x01(\x0b\x32\x17.bnet.protocol.EntityId\x12*\n\ttarget_id\x18\x02 \x02(\x0b\x32\x17.bnet.protocol.EntityId\x12\x0c\n\x04type\x18\x03 \x02(\t\x12\x35\n\tattribute\x18\x04 \x03(\x0b\x32\".bnet.protocol.attribute.Attribute\x12\x32\n\x11sender_account_id\x18\x05 \x01(\x0b\x32\x17.bnet.protocol.EntityId\x12\x32\n\x11target_account_id\x18\x06 \x01(\x0b\x32\x17.bnet.protocol.EntityId\x12\x19\n\x11sender_battle_tag\x18\x07 \x01(\t\"?\n\x11\x46indClientRequest\x12*\n\tentity_id\x18\x01 \x02(\x0b\x32\x17.bnet.protocol.EntityId\"X\n\x12\x46indClientResponse\x12\r\n\x05label\x18\x01 \x02(\r\x12\x33\n\x11\x63lient_process_id\x18\x02 \x01(\x0b\x32\x18.bnet.protocol.ProcessId\"C\n\x15RegisterClientRequest\x12*\n\tentity_id\x18\x01 \x02(\x0b\x32\x17.bnet.protocol.EntityId\"E\n\x17UnregisterClientRequest\x12*\n\tentity_id\x18\x01 \x02(\x0b\x32\x17.bnet.protocol.EntityId')
  ,
  dependencies=[bnet.attribute_pb2.DESCRIPTOR,bnet.entity_pb2.DESCRIPTOR,bnet.rpc_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_NOTIFICATION = _descriptor.Descriptor(
  name='Notification',
  full_name='bnet.protocol.notification.Notification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender_id', full_name='bnet.protocol.notification.Notification.sender_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_id', full_name='bnet.protocol.notification.Notification.target_id', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='bnet.protocol.notification.Notification.type', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attribute', full_name='bnet.protocol.notification.Notification.attribute', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sender_account_id', full_name='bnet.protocol.notification.Notification.sender_account_id', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_account_id', full_name='bnet.protocol.notification.Notification.target_account_id', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sender_battle_tag', full_name='bnet.protocol.notification.Notification.sender_battle_tag', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_battle_tag', full_name='bnet.protocol.notification.Notification.target_battle_tag', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='smth', full_name='bnet.protocol.notification.Notification.smth1', index=8,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=423,
)


_FINDCLIENTREQUEST = _descriptor.Descriptor(
  name='FindClientRequest',
  full_name='bnet.protocol.notification.FindClientRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity_id', full_name='bnet.protocol.notification.FindClientRequest.entity_id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=488,
)


_FINDCLIENTRESPONSE = _descriptor.Descriptor(
  name='FindClientResponse',
  full_name='bnet.protocol.notification.FindClientResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='bnet.protocol.notification.FindClientResponse.label', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_process_id', full_name='bnet.protocol.notification.FindClientResponse.client_process_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=490,
  serialized_end=578,
)


_REGISTERCLIENTREQUEST = _descriptor.Descriptor(
  name='RegisterClientRequest',
  full_name='bnet.protocol.notification.RegisterClientRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity_id', full_name='bnet.protocol.notification.RegisterClientRequest.entity_id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=580,
  serialized_end=647,
)


_UNREGISTERCLIENTREQUEST = _descriptor.Descriptor(
  name='UnregisterClientRequest',
  full_name='bnet.protocol.notification.UnregisterClientRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity_id', full_name='bnet.protocol.notification.UnregisterClientRequest.entity_id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=649,
  serialized_end=718,
)

_NOTIFICATION.fields_by_name['sender_id'].message_type = bnet.entity_pb2._ENTITYID
_NOTIFICATION.fields_by_name['target_id'].message_type = bnet.entity_pb2._ENTITYID
_NOTIFICATION.fields_by_name['attribute'].message_type = bnet.attribute_pb2._ATTRIBUTE
_NOTIFICATION.fields_by_name['sender_account_id'].message_type = bnet.entity_pb2._ENTITYID
_NOTIFICATION.fields_by_name['target_account_id'].message_type = bnet.entity_pb2._ENTITYID
_NOTIFICATION.fields_by_name['smth'].message_type = bnet.smth_pb2._SOMETHING
_FINDCLIENTREQUEST.fields_by_name['entity_id'].message_type = bnet.entity_pb2._ENTITYID
_FINDCLIENTRESPONSE.fields_by_name['client_process_id'].message_type = bnet.rpc_pb2._PROCESSID
_REGISTERCLIENTREQUEST.fields_by_name['entity_id'].message_type = bnet.entity_pb2._ENTITYID
_UNREGISTERCLIENTREQUEST.fields_by_name['entity_id'].message_type = bnet.entity_pb2._ENTITYID
DESCRIPTOR.message_types_by_name['Notification'] = _NOTIFICATION
DESCRIPTOR.message_types_by_name['FindClientRequest'] = _FINDCLIENTREQUEST
DESCRIPTOR.message_types_by_name['FindClientResponse'] = _FINDCLIENTRESPONSE
DESCRIPTOR.message_types_by_name['RegisterClientRequest'] = _REGISTERCLIENTREQUEST
DESCRIPTOR.message_types_by_name['UnregisterClientRequest'] = _UNREGISTERCLIENTREQUEST

Notification = _reflection.GeneratedProtocolMessageType('Notification', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFICATION,
  __module__ = 'bnet.notification_service_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.notification.Notification)
  ))
_sym_db.RegisterMessage(Notification)

FindClientRequest = _reflection.GeneratedProtocolMessageType('FindClientRequest', (_message.Message,), dict(
  DESCRIPTOR = _FINDCLIENTREQUEST,
  __module__ = 'bnet.notification_service_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.notification.FindClientRequest)
  ))
_sym_db.RegisterMessage(FindClientRequest)

FindClientResponse = _reflection.GeneratedProtocolMessageType('FindClientResponse', (_message.Message,), dict(
  DESCRIPTOR = _FINDCLIENTRESPONSE,
  __module__ = 'bnet.notification_service_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.notification.FindClientResponse)
  ))
_sym_db.RegisterMessage(FindClientResponse)

RegisterClientRequest = _reflection.GeneratedProtocolMessageType('RegisterClientRequest', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERCLIENTREQUEST,
  __module__ = 'bnet.notification_service_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.notification.RegisterClientRequest)
  ))
_sym_db.RegisterMessage(RegisterClientRequest)

UnregisterClientRequest = _reflection.GeneratedProtocolMessageType('UnregisterClientRequest', (_message.Message,), dict(
  DESCRIPTOR = _UNREGISTERCLIENTREQUEST,
  __module__ = 'bnet.notification_service_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.notification.UnregisterClientRequest)
  ))
_sym_db.RegisterMessage(UnregisterClientRequest)


# @@protoc_insertion_point(module_scope)
