# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bnet/presence_types.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bnet import attribute_pb2 as bnet_dot_attribute__pb2
from bnet import channel_types_pb2 as bnet_dot_channel__types__pb2
from bnet import entity_pb2 as bnet_dot_entity__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bnet/presence_types.proto',
  package='bnet.protocol.presence',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x19\x62net/presence_types.proto\x12\x16\x62net.protocol.presence\x1a\x14\x62net/attribute.proto\x1a\x18\x62net/channel_types.proto\x1a\x11\x62net/entity.proto\"D\n\x0cRichPresence\x12\x12\n\nprogram_id\x18\x01 \x02(\x07\x12\x11\n\tstream_id\x18\x02 \x02(\x07\x12\r\n\x05index\x18\x03 \x02(\r\"K\n\x08\x46ieldKey\x12\x0f\n\x07program\x18\x01 \x02(\r\x12\r\n\x05group\x18\x02 \x02(\r\x12\r\n\x05\x66ield\x18\x03 \x02(\r\x12\x10\n\x05index\x18\x04 \x01(\x04:\x01\x30\"g\n\x05\x46ield\x12-\n\x03key\x18\x01 \x02(\x0b\x32 .bnet.protocol.presence.FieldKey\x12/\n\x05value\x18\x02 \x02(\x0b\x32 .bnet.protocol.attribute.Variant\"\xb1\x01\n\x0e\x46ieldOperation\x12,\n\x05\x66ield\x18\x01 \x02(\x0b\x32\x1d.bnet.protocol.presence.Field\x12L\n\toperation\x18\x02 \x01(\x0e\x32\x34.bnet.protocol.presence.FieldOperation.OperationType:\x03SET\"#\n\rOperationType\x12\x07\n\x03SET\x10\x00\x12\t\n\x05\x43LEAR\x10\x01\"\xf0\x01\n\x0c\x43hannelState\x12*\n\tentity_id\x18\x01 \x01(\x0b\x32\x17.bnet.protocol.EntityId\x12?\n\x0f\x66ield_operation\x18\x02 \x03(\x0b\x32&.bnet.protocol.presence.FieldOperation\x12\x16\n\x07healing\x18\x03 \x01(\x08:\x05\x66\x61lse2[\n\x08presence\x12#.bnet.protocol.channel.ChannelState\x18\x65 \x01(\x0b\x32$.bnet.protocol.presence.ChannelState'
  ,
  dependencies=[bnet_dot_attribute__pb2.DESCRIPTOR,bnet_dot_channel__types__pb2.DESCRIPTOR,bnet_dot_entity__pb2.DESCRIPTOR,])



_FIELDOPERATION_OPERATIONTYPE = _descriptor.EnumDescriptor(
  name='OperationType',
  full_name='bnet.protocol.presence.FieldOperation.OperationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLEAR', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=515,
  serialized_end=550,
)
_sym_db.RegisterEnumDescriptor(_FIELDOPERATION_OPERATIONTYPE)


_RICHPRESENCE = _descriptor.Descriptor(
  name='RichPresence',
  full_name='bnet.protocol.presence.RichPresence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='program_id', full_name='bnet.protocol.presence.RichPresence.program_id', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stream_id', full_name='bnet.protocol.presence.RichPresence.stream_id', index=1,
      number=2, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='bnet.protocol.presence.RichPresence.index', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=188,
)


_FIELDKEY = _descriptor.Descriptor(
  name='FieldKey',
  full_name='bnet.protocol.presence.FieldKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='program', full_name='bnet.protocol.presence.FieldKey.program', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group', full_name='bnet.protocol.presence.FieldKey.group', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field', full_name='bnet.protocol.presence.FieldKey.field', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='bnet.protocol.presence.FieldKey.index', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=265,
)


_FIELD = _descriptor.Descriptor(
  name='Field',
  full_name='bnet.protocol.presence.Field',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='bnet.protocol.presence.Field.key', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='bnet.protocol.presence.Field.value', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=370,
)


_FIELDOPERATION = _descriptor.Descriptor(
  name='FieldOperation',
  full_name='bnet.protocol.presence.FieldOperation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field', full_name='bnet.protocol.presence.FieldOperation.field', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operation', full_name='bnet.protocol.presence.FieldOperation.operation', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FIELDOPERATION_OPERATIONTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=550,
)


_CHANNELSTATE = _descriptor.Descriptor(
  name='ChannelState',
  full_name='bnet.protocol.presence.ChannelState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity_id', full_name='bnet.protocol.presence.ChannelState.entity_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field_operation', full_name='bnet.protocol.presence.ChannelState.field_operation', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='healing', full_name='bnet.protocol.presence.ChannelState.healing', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='presence', full_name='bnet.protocol.presence.ChannelState.presence', index=0,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=553,
  serialized_end=793,
)

_FIELD.fields_by_name['key'].message_type = _FIELDKEY
_FIELD.fields_by_name['value'].message_type = bnet_dot_attribute__pb2._VARIANT
_FIELDOPERATION.fields_by_name['field'].message_type = _FIELD
_FIELDOPERATION.fields_by_name['operation'].enum_type = _FIELDOPERATION_OPERATIONTYPE
_FIELDOPERATION_OPERATIONTYPE.containing_type = _FIELDOPERATION
_CHANNELSTATE.fields_by_name['entity_id'].message_type = bnet_dot_entity__pb2._ENTITYID
_CHANNELSTATE.fields_by_name['field_operation'].message_type = _FIELDOPERATION
DESCRIPTOR.message_types_by_name['RichPresence'] = _RICHPRESENCE
DESCRIPTOR.message_types_by_name['FieldKey'] = _FIELDKEY
DESCRIPTOR.message_types_by_name['Field'] = _FIELD
DESCRIPTOR.message_types_by_name['FieldOperation'] = _FIELDOPERATION
DESCRIPTOR.message_types_by_name['ChannelState'] = _CHANNELSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RichPresence = _reflection.GeneratedProtocolMessageType('RichPresence', (_message.Message,), {
  'DESCRIPTOR' : _RICHPRESENCE,
  '__module__' : 'bnet.presence_types_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.presence.RichPresence)
  })
_sym_db.RegisterMessage(RichPresence)

FieldKey = _reflection.GeneratedProtocolMessageType('FieldKey', (_message.Message,), {
  'DESCRIPTOR' : _FIELDKEY,
  '__module__' : 'bnet.presence_types_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.presence.FieldKey)
  })
_sym_db.RegisterMessage(FieldKey)

Field = _reflection.GeneratedProtocolMessageType('Field', (_message.Message,), {
  'DESCRIPTOR' : _FIELD,
  '__module__' : 'bnet.presence_types_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.presence.Field)
  })
_sym_db.RegisterMessage(Field)

FieldOperation = _reflection.GeneratedProtocolMessageType('FieldOperation', (_message.Message,), {
  'DESCRIPTOR' : _FIELDOPERATION,
  '__module__' : 'bnet.presence_types_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.presence.FieldOperation)
  })
_sym_db.RegisterMessage(FieldOperation)

ChannelState = _reflection.GeneratedProtocolMessageType('ChannelState', (_message.Message,), {
  'DESCRIPTOR' : _CHANNELSTATE,
  '__module__' : 'bnet.presence_types_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.presence.ChannelState)
  })
_sym_db.RegisterMessage(ChannelState)

_CHANNELSTATE.extensions_by_name['presence'].message_type = _CHANNELSTATE
bnet_dot_channel__types__pb2.ChannelState.RegisterExtension(_CHANNELSTATE.extensions_by_name['presence'])

# @@protoc_insertion_point(module_scope)
