# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bnet/profanity.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bnet/profanity.proto',
  package='bnet.protocol.profanity',
  serialized_pb=_b('\n\x14\x62net/profanity.proto\x12\x17\x62net.protocol.profanity\")\n\nWordFilter\x12\x0c\n\x04type\x18\x01 \x02(\t\x12\r\n\x05regex\x18\x02 \x02(\t\"C\n\x0bWordFilters\x12\x34\n\x07\x66ilters\x18\x01 \x03(\x0b\x32#.bnet.protocol.profanity.WordFilter')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WORDFILTER = _descriptor.Descriptor(
  name='WordFilter',
  full_name='bnet.protocol.profanity.WordFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='bnet.protocol.profanity.WordFilter.type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='regex', full_name='bnet.protocol.profanity.WordFilter.regex', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=90,
)


_WORDFILTERS = _descriptor.Descriptor(
  name='WordFilters',
  full_name='bnet.protocol.profanity.WordFilters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filters', full_name='bnet.protocol.profanity.WordFilters.filters', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=159,
)

_WORDFILTERS.fields_by_name['filters'].message_type = _WORDFILTER
DESCRIPTOR.message_types_by_name['WordFilter'] = _WORDFILTER
DESCRIPTOR.message_types_by_name['WordFilters'] = _WORDFILTERS

WordFilter = _reflection.GeneratedProtocolMessageType('WordFilter', (_message.Message,), dict(
  DESCRIPTOR = _WORDFILTER,
  __module__ = 'bnet.profanity_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.profanity.WordFilter)
  ))
_sym_db.RegisterMessage(WordFilter)

WordFilters = _reflection.GeneratedProtocolMessageType('WordFilters', (_message.Message,), dict(
  DESCRIPTOR = _WORDFILTERS,
  __module__ = 'bnet.profanity_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.profanity.WordFilters)
  ))
_sym_db.RegisterMessage(WordFilters)


# @@protoc_insertion_point(module_scope)
