# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bnet/role.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bnet.attribute_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bnet/role.proto',
  package='bnet.protocol',
  serialized_pb=_b('\n\x0f\x62net/role.proto\x12\rbnet.protocol\x1a\x14\x62net/attribute.proto\"(\n\tPrivilege\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\r\"f\n\rRoleSetConfig\x12+\n\tprivilege\x18\x01 \x03(\x0b\x32\x18.bnet.protocol.Privilege\x12(\n\x08role_set\x18\x02 \x02(\x0b\x32\x16.bnet.protocol.RoleSet\"\xd0\x01\n\x04Role\x12\n\n\x02id\x18\x01 \x02(\r\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x11\n\tprivilege\x18\x03 \x03(\t\x12\x1b\n\x0f\x61ssignable_role\x18\x04 \x03(\rB\x02\x10\x01\x12\x17\n\x08required\x18\x05 \x01(\x08:\x05\x66\x61lse\x12\x15\n\x06unique\x18\x06 \x01(\x08:\x05\x66\x61lse\x12\x17\n\x0frelegation_role\x18\x07 \x01(\r\x12\x35\n\tattribute\x18\x08 \x03(\x0b\x32\".bnet.protocol.attribute.Attribute\"\xce\x01\n\x07RoleSet\x12\x0f\n\x07program\x18\x01 \x02(\t\x12\x0f\n\x07service\x18\x02 \x02(\t\x12\x18\n\x07subtype\x18\x03 \x01(\t:\x07\x64\x65\x66\x61ult\x12!\n\x04role\x18\x04 \x03(\x0b\x32\x13.bnet.protocol.Role\x12\x18\n\x0c\x64\x65\x66\x61ult_role\x18\x05 \x03(\rB\x02\x10\x01\x12\x13\n\x0bmax_members\x18\x06 \x01(\x05\x12\x35\n\tattribute\x18\x07 \x03(\x0b\x32\".bnet.protocol.attribute.Attribute')
  ,
  dependencies=[bnet.attribute_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PRIVILEGE = _descriptor.Descriptor(
  name='Privilege',
  full_name='bnet.protocol.Privilege',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='bnet.protocol.Privilege.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='bnet.protocol.Privilege.value', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=96,
)


_ROLESETCONFIG = _descriptor.Descriptor(
  name='RoleSetConfig',
  full_name='bnet.protocol.RoleSetConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='privilege', full_name='bnet.protocol.RoleSetConfig.privilege', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='role_set', full_name='bnet.protocol.RoleSetConfig.role_set', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=200,
)


_ROLE = _descriptor.Descriptor(
  name='Role',
  full_name='bnet.protocol.Role',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='bnet.protocol.Role.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='bnet.protocol.Role.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='privilege', full_name='bnet.protocol.Role.privilege', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='assignable_role', full_name='bnet.protocol.Role.assignable_role', index=3,
      number=4, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='required', full_name='bnet.protocol.Role.required', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unique', full_name='bnet.protocol.Role.unique', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='relegation_role', full_name='bnet.protocol.Role.relegation_role', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attribute', full_name='bnet.protocol.Role.attribute', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=411,
)


_ROLESET = _descriptor.Descriptor(
  name='RoleSet',
  full_name='bnet.protocol.RoleSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='program', full_name='bnet.protocol.RoleSet.program', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='service', full_name='bnet.protocol.RoleSet.service', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subtype', full_name='bnet.protocol.RoleSet.subtype', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("default").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='role', full_name='bnet.protocol.RoleSet.role', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='default_role', full_name='bnet.protocol.RoleSet.default_role', index=4,
      number=5, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='max_members', full_name='bnet.protocol.RoleSet.max_members', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attribute', full_name='bnet.protocol.RoleSet.attribute', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=620,
)

_ROLESETCONFIG.fields_by_name['privilege'].message_type = _PRIVILEGE
_ROLESETCONFIG.fields_by_name['role_set'].message_type = _ROLESET
_ROLE.fields_by_name['attribute'].message_type = bnet.attribute_pb2._ATTRIBUTE
_ROLESET.fields_by_name['role'].message_type = _ROLE
_ROLESET.fields_by_name['attribute'].message_type = bnet.attribute_pb2._ATTRIBUTE
DESCRIPTOR.message_types_by_name['Privilege'] = _PRIVILEGE
DESCRIPTOR.message_types_by_name['RoleSetConfig'] = _ROLESETCONFIG
DESCRIPTOR.message_types_by_name['Role'] = _ROLE
DESCRIPTOR.message_types_by_name['RoleSet'] = _ROLESET

Privilege = _reflection.GeneratedProtocolMessageType('Privilege', (_message.Message,), dict(
  DESCRIPTOR = _PRIVILEGE,
  __module__ = 'bnet.role_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.Privilege)
  ))
_sym_db.RegisterMessage(Privilege)

RoleSetConfig = _reflection.GeneratedProtocolMessageType('RoleSetConfig', (_message.Message,), dict(
  DESCRIPTOR = _ROLESETCONFIG,
  __module__ = 'bnet.role_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.RoleSetConfig)
  ))
_sym_db.RegisterMessage(RoleSetConfig)

Role = _reflection.GeneratedProtocolMessageType('Role', (_message.Message,), dict(
  DESCRIPTOR = _ROLE,
  __module__ = 'bnet.role_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.Role)
  ))
_sym_db.RegisterMessage(Role)

RoleSet = _reflection.GeneratedProtocolMessageType('RoleSet', (_message.Message,), dict(
  DESCRIPTOR = _ROLESET,
  __module__ = 'bnet.role_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.RoleSet)
  ))
_sym_db.RegisterMessage(RoleSet)


_ROLE.fields_by_name['assignable_role'].has_options = True
_ROLE.fields_by_name['assignable_role']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_ROLESET.fields_by_name['default_role'].has_options = True
_ROLESET.fields_by_name['default_role']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
