# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smth.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='smth.proto',
  package='bnet.protocol',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\nsmth.proto\x12\rbnet.protocol\".\n\rSubSomething1\x12\x1d\n\x15target_account_id_low\x18\x01 \x02(\x07\">\n\rSubSomething2\x12\x15\n\rtarget_id_low\x18\x01 \x02(\x07\x12\n\n\x02\x66\x32\x18\x02 \x02(\x07\x12\n\n\x02\x66\x33\x18\x03 \x02(\x05\"_\n\tSomething\x12(\n\x02\x66\x31\x18\x01 \x02(\x0b\x32\x1c.bnet.protocol.SubSomething1\x12(\n\x02\x66\x32\x18\x02 \x02(\x0b\x32\x1c.bnet.protocol.SubSomething2')
)




_SUBSOMETHING1 = _descriptor.Descriptor(
  name='SubSomething1',
  full_name='bnet.protocol.SubSomething1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_account_id_low', full_name='bnet.protocol.SubSomething1.target_account_id_low', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=75,
)


_SUBSOMETHING2 = _descriptor.Descriptor(
  name='SubSomething2',
  full_name='bnet.protocol.SubSomething2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_id_low', full_name='bnet.protocol.SubSomething2.target_id_low', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='f2', full_name='bnet.protocol.SubSomething2.f2', index=1,
      number=2, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='f3', full_name='bnet.protocol.SubSomething2.f3', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=139,
)


_SOMETHING = _descriptor.Descriptor(
  name='Something',
  full_name='bnet.protocol.Something',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='f1', full_name='bnet.protocol.Something.f1', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='f2', full_name='bnet.protocol.Something.f2', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=236,
)

_SOMETHING.fields_by_name['f1'].message_type = _SUBSOMETHING1
_SOMETHING.fields_by_name['f2'].message_type = _SUBSOMETHING2
DESCRIPTOR.message_types_by_name['SubSomething1'] = _SUBSOMETHING1
DESCRIPTOR.message_types_by_name['SubSomething2'] = _SUBSOMETHING2
DESCRIPTOR.message_types_by_name['Something'] = _SOMETHING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubSomething1 = _reflection.GeneratedProtocolMessageType('SubSomething1', (_message.Message,), dict(
  DESCRIPTOR = _SUBSOMETHING1,
  __module__ = 'smth_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.SubSomething1)
  ))
_sym_db.RegisterMessage(SubSomething1)

SubSomething2 = _reflection.GeneratedProtocolMessageType('SubSomething2', (_message.Message,), dict(
  DESCRIPTOR = _SUBSOMETHING2,
  __module__ = 'smth_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.SubSomething2)
  ))
_sym_db.RegisterMessage(SubSomething2)

Something = _reflection.GeneratedProtocolMessageType('Something', (_message.Message,), dict(
  DESCRIPTOR = _SOMETHING,
  __module__ = 'smth_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.Something)
  ))
_sym_db.RegisterMessage(Something)


# @@protoc_insertion_point(module_scope)
